import { writeFileSync, mkdirSync, existsSync, copyFileSync } from 'fs';
import { join } from 'path';
import { Logger } from '../ui/logger.js';
import { Spinner } from '../ui/spinner.js';
import inquirer from 'inquirer';

interface InitOptions {
  example?: boolean;
  provider?: 'gemini' | 'claude' | 'llamacpp';
}

export async function initCommand(projectName?: string, options: InitOptions = {}) {
  try {
    Logger.header('Initialize SpecFlow Project');

    // Get project name if not provided
    if (!projectName) {
      const answer = await inquirer.prompt([
        {
          type: 'input',
          name: 'name',
          message: 'Project name:',
          default: 'my-api',
          validate: (input: string) => {
            if (!input.trim()) {
              return 'Project name is required';
            }
            return true;
          }
        }
      ]);
      projectName = answer.name;
    }

    // At this point, projectName is guaranteed to be defined
    const finalProjectName: string = projectName!;

    // Check if we're in the project directory or need to create it
    const currentDir = process.cwd();
    const projectDir = join(currentDir, finalProjectName);
    const useCurrentDir = currentDir.endsWith(finalProjectName) || finalProjectName === '.';
    
    const workingDir = useCurrentDir ? currentDir : projectDir;

    if (!useCurrentDir) {
      if (existsSync(projectDir)) {
        Logger.error(`Directory '${finalProjectName}' already exists`);
        return;
      }
      mkdirSync(projectDir, { recursive: true });
      Logger.success(`Created directory: ${finalProjectName}`);
    }

    await Spinner.withSpinner('Setting up project structure...', async (spinner) => {
      // Create directory structure
      const dirs = [
        'requirements/business',
        'requirements/technical', 
        'requirements/schemas'
      ];

      for (const dir of dirs) {
        mkdirSync(join(workingDir, dir), { recursive: true });
      }

      spinner.updateText('Creating configuration files...');

      // Create specflow.config.yaml
      const config = createConfigFile(finalProjectName, options.provider || 'gemini');
      writeFileSync(join(workingDir, 'specflow.config.yaml'), config);

      // Create .gitignore
      const gitignore = createGitignoreFile();
      writeFileSync(join(workingDir, '.gitignore'), gitignore);

      // Create README.md
      const readme = createReadmeFile(finalProjectName);
      writeFileSync(join(workingDir, 'README.md'), readme);

      if (options.example) {
        spinner.updateText('Adding example specifications...');
        await createExampleSpecs(workingDir);
      }
    });

    Logger.success('Project initialized successfully!');
    
    // Show next steps
    Logger.header('Next Steps');
    
    if (!useCurrentDir) {
      Logger.info(`1. cd ${finalProjectName}`);
    } else {
      Logger.info('1. You\'re in the project directory');
    }

    if (options.example) {
      Logger.info('2. Review the example specs in requirements/');
      Logger.info('3. Run `specflow prepare` to refine the specifications');
    } else {
      Logger.info('2. Create your rough specifications in requirements/');
      Logger.info('   • Add .md files with your API ideas (bullet points, notes, anything!)');
      Logger.info('3. Run `specflow prepare` to transform them into professional specs');
    }
    
    Logger.info('4. Run `specflow generate` to create the backend code');
    Logger.info('5. Run `specflow dev` to start the development server');

    // Show LLM setup reminder
    const hasApiKey = process.env.GEMINI_API_KEY || process.env.ANTHROPIC_API_KEY || process.env.LLAMACPP_API_KEY;
    if (!hasApiKey) {
      Logger.divider();
      Logger.warning('LLM API Key Required');
      Logger.info('To use `specflow prepare`, you\'ll need an LLM provider API key:');
      Logger.info('• Gemini (free): https://ai.google.dev');
      Logger.info('• Claude: https://console.anthropic.com');
      Logger.info('• Or run local LlamaCpp');
    }

  } catch (error) {
    Logger.error(`Failed to initialize project: ${error instanceof Error ? error.message : 'Unknown error'}`);
    process.exit(1);
  }
}

function createConfigFile(projectName: string, provider: string): string {
  return `# SpecFlow Configuration
version: "1.0"

# Project info
project:
  name: "${projectName}"
  description: "API generated by SpecFlow"
  version: "1.0.0"

# LLM Provider for spec preparation and code generation
llm:
  provider: "${provider}"           # gemini | claude | llamacpp
  model: ""                        # auto-selects best model per provider
  apiKey: ""                       # or set via GEMINI_API_KEY / ANTHROPIC_API_KEY env var

# Generation output
output:
  directory: "./generated"         # where generated code goes
  runtime: "bun"                   # bun (default)
  framework: "hono"                # hono (default)
  orm: "drizzle"                   # drizzle (default)
  database: "postgresql"           # postgresql (default)
  includeDocker: true              # generate Dockerfile + docker-compose.yml
  includeTests: false              # generate test files (Phase 2)

# Requirements location
requirements:
  directory: "./requirements"      # where spec files live
  businessDir: "business"          # subdirectory for .req.md files
  technicalDir: "technical"        # subdirectory for .contract.md files
  schemasDir: "schemas"            # subdirectory for shared JSON schemas
`;
}

function createGitignoreFile(): string {
  return `# Dependencies
node_modules/
.pnp
.pnp.js

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Generated code
generated/
dist/
build/

# OS
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# SpecFlow
.specflow-prepared
`;
}

function createReadmeFile(projectName: string): string {
  return `# ${projectName}

API backend generated by [SpecFlow](https://github.com/suhailtajshaik/specflow).

## Quick Start

1. **Write rough specifications** in \`requirements/\`:
   - Add any .md files with your API ideas
   - Use bullet points, plain English, whatever works for you

2. **Transform into professional specs**:
   \`\`\`bash
   specflow prepare
   \`\`\`
   This analyzes your rough input and creates detailed .req.md and .contract.md files.

3. **Generate production code**:
   \`\`\`bash
   specflow generate
   \`\`\`
   Creates a complete TypeScript backend with Hono + Drizzle + PostgreSQL.

4. **Start development**:
   \`\`\`bash
   specflow dev
   \`\`\`

## Project Structure

\`\`\`
requirements/
├── business/          # Business requirement files (.req.md)
├── technical/         # API contract files (.contract.md)  
└── schemas/           # Shared JSON schemas

generated/             # Generated backend code (after specflow generate)
├── src/
│   ├── routes/
│   ├── schemas/
│   ├── db/
│   └── server.ts
├── package.json
├── Dockerfile
└── docker-compose.yml
\`\`\`

## Commands

- \`specflow init\` - Initialize new project
- \`specflow prepare\` - Transform rough specs into professional documentation
- \`specflow generate\` - Generate production TypeScript backend
- \`specflow dev\` - Generate + start development server  
- \`specflow list\` - List all API endpoints
- \`specflow setup\` - Check setup and installation help

## Configuration

Edit \`specflow.config.yaml\` to customize:
- LLM provider (Gemini, Claude, local LlamaCpp)
- Output directory and tech stack
- Database settings
- Docker configuration

## Need Help?

- Check \`specflow setup\` for installation issues
- Example specs: \`specflow init --example\`
- Documentation: [SpecFlow GitHub](https://github.com/suhailtajshaik/specflow)
`;
}

async function createExampleSpecs(workingDir: string): Promise<void> {
  // Create example business requirements
  const userRegistrationReq = `# User Registration Ideas

Just some rough notes on user registration:

- Users should be able to sign up with email and password
- Need to validate emails are real
- Passwords should be secure (not sure exact rules yet)
- Send verification email after signup
- Don't allow duplicate emails
- Return user info after successful registration

## Security thoughts
- Rate limit registration attempts
- Hash passwords obviously
- Maybe block disposable email domains?

## Questions
- What happens if verification email fails to send?
- Should we allow social login later?
`;

  const createOrderReq = `# Order Creation

Basic e-commerce order flow:

• User must be logged in
• User selects products and quantities  
• System calculates total price
• User provides payment info
• System processes payment
• Order is created and confirmed
• User gets order confirmation

**Business rules:**
- Check product stock before creating order
- Don't trust price from client - calculate server-side
- Reserve inventory during order process
- Handle payment failures gracefully
- Send confirmation email

**Edge cases:**
- What if product goes out of stock during checkout?
- Payment succeeds but email fails?
- User closes browser during payment?
`;

  writeFileSync(
    join(workingDir, 'requirements/user-registration-notes.md'), 
    userRegistrationReq
  );

  writeFileSync(
    join(workingDir, 'requirements/order-creation-ideas.md'), 
    createOrderReq
  );

  // Create a simple schema example
  const userSchema = {
    type: "object",
    properties: {
      id: { type: "string", format: "uuid" },
      email: { type: "string", format: "email" },
      firstName: { type: "string" },
      lastName: { type: "string" }
    }
  };

  writeFileSync(
    join(workingDir, 'requirements/schemas/user-basic.json'),
    JSON.stringify(userSchema, null, 2)
  );
}