import type { SpecFlowConfig } from './types.js';

export const DEFAULT_CONFIG: SpecFlowConfig = {
  version: "1.0",
  project: {
    name: "my-api",
    description: "API generated by SpecFlow",
    version: "1.0.0"
  },
  llm: {
    provider: "gemini"
  },
  output: {
    directory: "./generated",
    runtime: "bun",
    framework: "hono",
    orm: "drizzle",
    database: "postgresql",
    includeDocker: true,
    includeTests: false
  },
  requirements: {
    directory: "./requirements",
    businessDir: "business",
    technicalDir: "technical",
    schemasDir: "schemas"
  }
};