import type { SpecFlowConfig } from '../config/types.js';
import type { GeneratedFile } from './index.js';

export class ScaffoldGenerator {
  async generate(config: SpecFlowConfig): Promise<GeneratedFile[]> {
    const files: GeneratedFile[] = [];
    
    // Core application files
    files.push(this.generatePackageJson(config));
    files.push(this.generateTsConfig());
    files.push(this.generateDrizzleConfig());
    files.push(this.generateEnvExample());
    
    // Database setup
    files.push(this.generateDbClient());
    files.push(this.generateMigrationRunner());
    
    // Middleware
    files.push(this.generateAuthMiddleware());
    files.push(this.generateCorsMiddleware());
    files.push(this.generateRateLimitMiddleware());
    
    // Utility libraries
    files.push(this.generateErrorHandler());
    files.push(this.generatePasswordUtils());
    files.push(this.generateAuthUtils());
    
    // Docker setup
    if (config.output.includeDocker) {
      files.push(this.generateDockerfile());
      files.push(this.generateDockerCompose());
      files.push(this.generateDockerIgnore());
    }
    
    // Additional config files
    files.push(this.generateGitIgnore());
    files.push(this.generateReadme(config));
    
    return files;
  }

  private generatePackageJson(config: SpecFlowConfig): GeneratedFile {
    const packageJson = {
      name: `${config.project.name}-api`,
      version: config.project.version || '1.0.0',
      description: config.project.description || 'API generated by SpecFlow',
      type: 'module',
      scripts: {
        dev: 'bun run --watch src/server.ts',
        start: 'bun run src/server.ts',
        build: 'bun build src/server.ts --outdir=dist --target=bun',
        test: 'bun test',
        'test:watch': 'bun test --watch',
        'db:generate': 'bunx drizzle-kit generate',
        'db:migrate': 'bunx drizzle-kit migrate',
        'db:push': 'bunx drizzle-kit push',
        'db:studio': 'bunx drizzle-kit studio',
        'db:reset': 'bun run src/db/reset.ts',
        typecheck: 'bunx tsc --noEmit',
        lint: 'bunx eslint src/**/*.ts',
        format: 'bunx prettier --write src/**/*.ts'
      },
      dependencies: {
        'hono': '^4.0.0',
        'drizzle-orm': '^0.39.0',
        'postgres': '^3.4.0',
        '@types/bun': 'latest',
        'zod': '^3.23.0',
        'bcrypt': '^5.1.0',
        'jsonwebtoken': '^9.0.0',
        '@types/bcrypt': '^5.0.0',
        '@types/jsonwebtoken': '^9.0.0',
        'gray-matter': '^4.0.3'
      },
      devDependencies: {
        'drizzle-kit': '^0.30.0',
        'typescript': '^5.5.0',
        '@types/node': '^20.0.0',
        'eslint': '^8.57.0',
        '@typescript-eslint/eslint-plugin': '^6.21.0',
        '@typescript-eslint/parser': '^6.21.0',
        'prettier': '^3.2.5'
      }
    };

    return {
      path: 'package.json',
      content: JSON.stringify(packageJson, null, 2) + '\n',
      type: 'config'
    };
  }

  private generateTsConfig(): GeneratedFile {
    const tsConfig = {
      compilerOptions: {
        target: 'ES2022',
        lib: ['ES2022'],
        module: 'ESNext',
        moduleResolution: 'bundler',
        allowImportingTsExtensions: true,
        noEmit: true,
        composite: false,
        strict: true,
        downlevelIteration: true,
        skipLibCheck: true,
        jsx: 'preserve',
        allowSyntheticDefaultImports: true,
        forceConsistentCasingInFileNames: true,
        allowJs: true,
        types: ['bun-types']
      },
      include: ['src/**/*'],
      exclude: ['node_modules', 'dist']
    };

    return {
      path: 'tsconfig.json',
      content: JSON.stringify(tsConfig, null, 2) + '\n',
      type: 'config'
    };
  }

  private generateDrizzleConfig(): GeneratedFile {
    const content = `import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  schema: './src/db/schema.ts',
  out: './drizzle',
  driver: 'pg',
  dbCredentials: {
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '5432'),
    user: process.env.DB_USER || 'postgres',
    password: process.env.DB_PASSWORD || 'postgres',
    database: process.env.DB_NAME || 'specflow_api',
    ssl: process.env.DB_SSL === 'true'
  },
  verbose: true,
  strict: true
});`;

    return {
      path: 'drizzle.config.ts',
      content,
      type: 'config'
    };
  }

  private generateEnvExample(): GeneratedFile {
    const content = `# Server Configuration
PORT=3000
NODE_ENV=development

# Database Configuration
DB_HOST=localhost
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=postgres
DB_NAME=specflow_api
DB_SSL=false
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/specflow_api

# Authentication
JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
JWT_EXPIRES_IN=7d

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# CORS Configuration
CORS_ORIGIN=http://localhost:3000,http://localhost:5173

# Email Configuration (if using email verification)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=your-email@gmail.com
SMTP_PASS=your-app-password
FROM_EMAIL=noreply@yourapp.com

# Redis Configuration (optional for caching/sessions)
REDIS_URL=redis://localhost:6379

# Log Level
LOG_LEVEL=info

# Bcrypt Rounds
BCRYPT_ROUNDS=12`;

    return {
      path: '.env.example',
      content,
      type: 'config'
    };
  }

  private generateDbClient(): GeneratedFile {
    const content = `import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import * as schema from './schema.js';

// Create the connection
const connectionString = process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/specflow_api';

const sql = postgres(connectionString, {
  max: parseInt(process.env.DB_POOL_SIZE || '20'),
  idle_timeout: parseInt(process.env.DB_IDLE_TIMEOUT || '30'),
  connect_timeout: parseInt(process.env.DB_CONNECT_TIMEOUT || '60'),
});

// Create the database instance
export const db = drizzle(sql, { schema });

// Health check function
export async function checkDatabaseConnection(): Promise<boolean> {
  try {
    await sql\`SELECT 1\`;
    return true;
  } catch (error) {
    console.error('Database connection failed:', error);
    return false;
  }
}

// Graceful shutdown
export async function closeDatabaseConnection(): Promise<void> {
  await sql.end();
}

// Handle process termination
process.on('SIGINT', closeDatabaseConnection);
process.on('SIGTERM', closeDatabaseConnection);`;

    return {
      path: 'src/db/client.ts',
      content,
      type: 'scaffold'
    };
  }

  private generateMigrationRunner(): GeneratedFile {
    const content = `import { migrate } from 'drizzle-orm/postgres-js/migrator';
import { db } from './client.js';

async function runMigrations() {
  console.log('🔄 Running migrations...');
  
  try {
    await migrate(db, { migrationsFolder: './drizzle' });
    console.log('✅ Migrations completed successfully');
  } catch (error) {
    console.error('❌ Migration failed:', error);
    process.exit(1);
  }
}

if (import.meta.main) {
  runMigrations();
}`;

    return {
      path: 'src/db/migrate.ts',
      content,
      type: 'scaffold'
    };
  }

  private generateAuthMiddleware(): GeneratedFile {
    const content = `import type { Context, Next } from 'hono';
import jwt from 'jsonwebtoken';
import { AppError } from '../lib/errors.js';

export interface AuthUser {
  id: string;
  email: string;
  role?: string;
}

declare module 'hono' {
  interface ContextVariableMap {
    user: AuthUser;
  }
}

export function authMiddleware(required: boolean = true) {
  return async (c: Context, next: Next) => {
    const authorization = c.req.header('Authorization');
    
    if (!authorization) {
      if (required) {
        throw new AppError(401, 'UNAUTHORIZED', 'Authorization header is required');
      }
      return next();
    }

    const token = authorization.startsWith('Bearer ') 
      ? authorization.slice(7) 
      : authorization;

    try {
      const jwtSecret = process.env.JWT_SECRET;
      if (!jwtSecret) {
        throw new Error('JWT_SECRET not configured');
      }

      const decoded = jwt.verify(token, jwtSecret) as AuthUser;
      c.set('user', decoded);
      
      return next();
    } catch (error) {
      if (required) {
        throw new AppError(401, 'UNAUTHORIZED', 'Invalid or expired token');
      }
      return next();
    }
  };
}

export function requireAuth() {
  return authMiddleware(true);
}

export function optionalAuth() {
  return authMiddleware(false);
}

export function requireRole(...roles: string[]) {
  return async (c: Context, next: Next) => {
    const user = c.get('user');
    
    if (!user) {
      throw new AppError(401, 'UNAUTHORIZED', 'Authentication required');
    }

    if (roles.length > 0 && !roles.includes(user.role || '')) {
      throw new AppError(403, 'FORBIDDEN', 'Insufficient permissions');
    }

    return next();
  };
}`;

    return {
      path: 'src/middleware/auth.ts',
      content,
      type: 'scaffold'
    };
  }

  private generateCorsMiddleware(): GeneratedFile {
    const content = `import type { Context, Next } from 'hono';

export interface CorsOptions {
  origin?: string | string[] | ((origin: string) => boolean);
  methods?: string[];
  allowedHeaders?: string[];
  credentials?: boolean;
  maxAge?: number;
}

export function corsMiddleware(options: CorsOptions = {}) {
  const {
    origin = process.env.CORS_ORIGIN?.split(',') || ['http://localhost:3000'],
    methods = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS'],
    allowedHeaders = ['Content-Type', 'Authorization'],
    credentials = true,
    maxAge = 86400
  } = options;

  return async (c: Context, next: Next) => {
    const requestOrigin = c.req.header('origin');
    
    // Handle preflight requests
    if (c.req.method === 'OPTIONS') {
      const headers = new Headers();
      
      // Set allowed origin
      if (Array.isArray(origin)) {
        if (origin.includes('*') || (requestOrigin && origin.includes(requestOrigin))) {
          headers.set('Access-Control-Allow-Origin', requestOrigin || '*');
        }
      } else if (typeof origin === 'string') {
        headers.set('Access-Control-Allow-Origin', origin);
      } else if (typeof origin === 'function') {
        if (requestOrigin && origin(requestOrigin)) {
          headers.set('Access-Control-Allow-Origin', requestOrigin);
        }
      }
      
      headers.set('Access-Control-Allow-Methods', methods.join(', '));
      headers.set('Access-Control-Allow-Headers', allowedHeaders.join(', '));
      headers.set('Access-Control-Max-Age', maxAge.toString());
      
      if (credentials) {
        headers.set('Access-Control-Allow-Credentials', 'true');
      }

      return c.newResponse(null, 200, headers);
    }

    // Set CORS headers for actual requests
    if (Array.isArray(origin)) {
      if (origin.includes('*') || (requestOrigin && origin.includes(requestOrigin))) {
        c.header('Access-Control-Allow-Origin', requestOrigin || '*');
      }
    } else if (typeof origin === 'string') {
      c.header('Access-Control-Allow-Origin', origin);
    } else if (typeof origin === 'function') {
      if (requestOrigin && origin(requestOrigin)) {
        c.header('Access-Control-Allow-Origin', requestOrigin);
      }
    }

    if (credentials) {
      c.header('Access-Control-Allow-Credentials', 'true');
    }

    return next();
  };
}`;

    return {
      path: 'src/middleware/cors.ts',
      content,
      type: 'scaffold'
    };
  }

  private generateRateLimitMiddleware(): GeneratedFile {
    const content = `import type { Context, Next } from 'hono';
import { AppError } from '../lib/errors.js';

interface RateLimitOptions {
  windowMs?: number;
  maxRequests?: number;
  message?: string;
  skipSuccessfulRequests?: boolean;
  skipFailedRequests?: boolean;
}

interface RateLimitStore {
  [key: string]: {
    count: number;
    resetTime: number;
  };
}

// In-memory store (in production, use Redis or database)
const store: RateLimitStore = {};

export function rateLimitMiddleware(options: RateLimitOptions = {}) {
  const {
    windowMs = parseInt(process.env.RATE_LIMIT_WINDOW_MS || '900000'), // 15 minutes
    maxRequests = parseInt(process.env.RATE_LIMIT_MAX_REQUESTS || '100'),
    message = 'Too many requests from this IP, please try again later',
    skipSuccessfulRequests = false,
    skipFailedRequests = false
  } = options;

  return async (c: Context, next: Next) => {
    const clientIp = getClientIP(c);
    const now = Date.now();
    const resetTime = now + windowMs;

    // Clean up expired entries
    cleanupExpiredEntries(now);

    // Get or create rate limit entry
    if (!store[clientIp]) {
      store[clientIp] = { count: 0, resetTime };
    }

    const entry = store[clientIp];

    // Reset if window has expired
    if (now > entry.resetTime) {
      entry.count = 0;
      entry.resetTime = resetTime;
    }

    // Check if limit exceeded
    if (entry.count >= maxRequests) {
      c.header('X-Rate-Limit-Limit', maxRequests.toString());
      c.header('X-Rate-Limit-Remaining', '0');
      c.header('X-Rate-Limit-Reset', Math.ceil(entry.resetTime / 1000).toString());
      c.header('Retry-After', Math.ceil((entry.resetTime - now) / 1000).toString());
      
      throw new AppError(429, 'RATE_LIMIT_EXCEEDED', message);
    }

    // Increment counter
    entry.count++;

    // Set rate limit headers
    c.header('X-Rate-Limit-Limit', maxRequests.toString());
    c.header('X-Rate-Limit-Remaining', (maxRequests - entry.count).toString());
    c.header('X-Rate-Limit-Reset', Math.ceil(entry.resetTime / 1000).toString());

    await next();

    // Optionally skip counting successful/failed requests
    const statusCode = c.res.status;
    if (
      (skipSuccessfulRequests && statusCode < 400) ||
      (skipFailedRequests && statusCode >= 400)
    ) {
      entry.count--;
    }
  };
}

function getClientIP(c: Context): string {
  // Try various headers for getting real client IP
  return (
    c.req.header('x-forwarded-for')?.split(',')[0] ||
    c.req.header('x-real-ip') ||
    c.req.header('cf-connecting-ip') ||
    c.env?.ip ||
    'unknown'
  );
}

function cleanupExpiredEntries(now: number): void {
  Object.keys(store).forEach(key => {
    if (store[key].resetTime <= now) {
      delete store[key];
    }
  });
}

// Specific rate limiters for different endpoints
export const authRateLimit = rateLimitMiddleware({
  windowMs: 15 * 60 * 1000, // 15 minutes
  maxRequests: 5, // 5 attempts per window
  message: 'Too many authentication attempts, please try again later'
});

export const registerRateLimit = rateLimitMiddleware({
  windowMs: 60 * 60 * 1000, // 1 hour
  maxRequests: 3, // 3 registrations per hour per IP
  message: 'Too many registration attempts, please try again later'
});`;

    return {
      path: 'src/middleware/rate-limit.ts',
      content,
      type: 'scaffold'
    };
  }

  private generateErrorHandler(): GeneratedFile {
    const content = `import type { Context } from 'hono';

export class AppError extends Error {
  public readonly status: number;
  public readonly code: string;
  public readonly details?: any;

  constructor(status: number, code: string, message: string, details?: any) {
    super(message);
    this.name = 'AppError';
    this.status = status;
    this.code = code;
    this.details = details;
    
    // Maintains proper stack trace for where our error was thrown
    Error.captureStackTrace?.(this, AppError);
  }
}

export function errorHandler(error: Error, c: Context) {
  console.error('Error occurred:', {
    message: error.message,
    stack: error.stack,
    url: c.req.url,
    method: c.req.method,
    timestamp: new Date().toISOString()
  });

  // Handle known application errors
  if (error instanceof AppError) {
    return c.json({
      error: {
        code: error.code,
        message: error.message,
        details: error.details
      }
    }, error.status);
  }

  // Handle Zod validation errors
  if (error.name === 'ZodError') {
    return c.json({
      error: {
        code: 'VALIDATION_ERROR',
        message: 'Invalid request data',
        details: {
          issues: (error as any).issues
        }
      }
    }, 400);
  }

  // Handle JWT errors
  if (error.name === 'JsonWebTokenError') {
    return c.json({
      error: {
        code: 'UNAUTHORIZED',
        message: 'Invalid token'
      }
    }, 401);
  }

  if (error.name === 'TokenExpiredError') {
    return c.json({
      error: {
        code: 'UNAUTHORIZED',
        message: 'Token expired'
      }
    }, 401);
  }

  // Handle database errors
  if (error.message.includes('duplicate key value violates unique constraint')) {
    return c.json({
      error: {
        code: 'CONFLICT',
        message: 'Resource already exists'
      }
    }, 409);
  }

  if (error.message.includes('foreign key constraint')) {
    return c.json({
      error: {
        code: 'INVALID_REFERENCE',
        message: 'Referenced resource does not exist'
      }
    }, 400);
  }

  // Handle unexpected errors
  return c.json({
    error: {
      code: 'INTERNAL_ERROR',
      message: process.env.NODE_ENV === 'production' 
        ? 'An unexpected error occurred' 
        : error.message
    }
  }, 500);
}

// Common error factory functions
export const errors = {
  notFound: (resource = 'Resource') => 
    new AppError(404, 'NOT_FOUND', \`\${resource} not found\`),
    
  unauthorized: (message = 'Authentication required') => 
    new AppError(401, 'UNAUTHORIZED', message),
    
  forbidden: (message = 'Access denied') => 
    new AppError(403, 'FORBIDDEN', message),
    
  validation: (message = 'Invalid input data', details?: any) => 
    new AppError(400, 'VALIDATION_ERROR', message, details),
    
  conflict: (message = 'Resource conflict') => 
    new AppError(409, 'CONFLICT', message),
    
  tooManyRequests: (message = 'Rate limit exceeded') => 
    new AppError(429, 'RATE_LIMIT_EXCEEDED', message),
    
  internal: (message = 'Internal server error') => 
    new AppError(500, 'INTERNAL_ERROR', message)
};`;

    return {
      path: 'src/lib/errors.ts',
      content,
      type: 'scaffold'
    };
  }

  private generatePasswordUtils(): GeneratedFile {
    const content = `import bcrypt from 'bcrypt';

const SALT_ROUNDS = parseInt(process.env.BCRYPT_ROUNDS || '12');

export async function hashPassword(password: string): Promise<string> {
  try {
    const hash = await bcrypt.hash(password, SALT_ROUNDS);
    return hash;
  } catch (error) {
    throw new Error('Failed to hash password');
  }
}

export async function comparePassword(password: string, hash: string): Promise<boolean> {
  try {
    const isValid = await bcrypt.compare(password, hash);
    return isValid;
  } catch (error) {
    throw new Error('Failed to compare password');
  }
}

export function generateSecureToken(length: number = 32): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  
  return result;
}

export function isStrongPassword(password: string): boolean {
  // At least 8 characters
  if (password.length < 8) return false;
  
  // Contains uppercase letter
  if (!/[A-Z]/.test(password)) return false;
  
  // Contains lowercase letter
  if (!/[a-z]/.test(password)) return false;
  
  // Contains digit
  if (!/\\d/.test(password)) return false;
  
  // Contains special character
  if (!/[@$!%*?&]/.test(password)) return false;
  
  return true;
}

export function getPasswordStrengthScore(password: string): {
  score: number;
  feedback: string[];
} {
  const feedback: string[] = [];
  let score = 0;

  if (password.length >= 8) {
    score += 20;
  } else {
    feedback.push('Password should be at least 8 characters long');
  }

  if (password.length >= 12) {
    score += 10;
  }

  if (/[a-z]/.test(password)) {
    score += 10;
  } else {
    feedback.push('Password should contain lowercase letters');
  }

  if (/[A-Z]/.test(password)) {
    score += 10;
  } else {
    feedback.push('Password should contain uppercase letters');
  }

  if (/\\d/.test(password)) {
    score += 15;
  } else {
    feedback.push('Password should contain numbers');
  }

  if (/[@$!%*?&]/.test(password)) {
    score += 15;
  } else {
    feedback.push('Password should contain special characters (@$!%*?&)');
  }

  if (/[^a-zA-Z0-9@$!%*?&]/.test(password)) {
    score += 5;
  }

  // Penalty for common patterns
  if (/123456|password|qwerty|admin/i.test(password)) {
    score -= 20;
    feedback.push('Avoid common password patterns');
  }

  // Penalty for repeated characters
  if (/(.)\\1{2,}/.test(password)) {
    score -= 10;
    feedback.push('Avoid repeated characters');
  }

  return {
    score: Math.max(0, Math.min(100, score)),
    feedback
  };
}`;

    return {
      path: 'src/lib/password.ts',
      content,
      type: 'scaffold'
    };
  }

  private generateAuthUtils(): GeneratedFile {
    const content = `import jwt from 'jsonwebtoken';
import type { AuthUser } from '../middleware/auth.js';

const JWT_SECRET = process.env.JWT_SECRET;
const JWT_EXPIRES_IN = process.env.JWT_EXPIRES_IN || '7d';

if (!JWT_SECRET) {
  throw new Error('JWT_SECRET environment variable is required');
}

export interface TokenPayload {
  id: string;
  email: string;
  role?: string;
}

export function generateJWT(payload: TokenPayload): string {
  return jwt.sign(payload, JWT_SECRET, {
    expiresIn: JWT_EXPIRES_IN,
    issuer: 'specflow-api',
    audience: 'specflow-client'
  });
}

export function verifyJWT(token: string): AuthUser {
  try {
    const decoded = jwt.verify(token, JWT_SECRET, {
      issuer: 'specflow-api',
      audience: 'specflow-client'
    }) as AuthUser;
    
    return decoded;
  } catch (error) {
    throw new Error('Invalid or expired token');
  }
}

export function generateRefreshToken(): string {
  return jwt.sign({}, JWT_SECRET, {
    expiresIn: '30d',
    issuer: 'specflow-api',
    audience: 'specflow-refresh'
  });
}

export function verifyRefreshToken(token: string): boolean {
  try {
    jwt.verify(token, JWT_SECRET, {
      issuer: 'specflow-api',
      audience: 'specflow-refresh'
    });
    return true;
  } catch (error) {
    return false;
  }
}

export function extractTokenFromHeader(authHeader?: string): string | null {
  if (!authHeader) return null;
  
  const parts = authHeader.split(' ');
  if (parts.length !== 2 || parts[0] !== 'Bearer') {
    return null;
  }
  
  return parts[1];
}

export function generateApiKey(prefix: string = 'sk'): string {
  const randomBytes = new Uint8Array(32);
  crypto.getRandomValues(randomBytes);
  const randomString = Array.from(randomBytes, byte => 
    byte.toString(16).padStart(2, '0')
  ).join('');
  
  return \`\${prefix}_\${randomString}\`;
}

export function validateEmail(email: string): boolean {
  const emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;
  return emailRegex.test(email.toLowerCase());
}

export function normalizeEmail(email: string): string {
  return email.toLowerCase().trim();
}

export function maskEmail(email: string): string {
  const [localPart, domain] = email.split('@');
  if (localPart.length <= 2) {
    return \`*@\${domain}\`;
  }
  
  const masked = localPart.charAt(0) + '*'.repeat(localPart.length - 2) + localPart.charAt(localPart.length - 1);
  return \`\${masked}@\${domain}\`;
}`;

    return {
      path: 'src/lib/auth.ts',
      content,
      type: 'scaffold'
    };
  }

  private generateDockerfile(): GeneratedFile {
    const content = `# Use the official Bun image as the base
FROM oven/bun:1 AS base

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json bun.lockb* ./

# Install dependencies
RUN bun install --frozen-lockfile --production

# Copy source code
COPY . .

# Build the application
RUN bun run build

# Production stage
FROM oven/bun:1-slim AS production

WORKDIR /app

# Copy package files
COPY package.json ./

# Install production dependencies only
RUN bun install --frozen-lockfile --production

# Copy built application
COPY --from=base /app/dist ./dist
COPY --from=base /app/drizzle ./drizzle

# Create non-root user
RUN addgroup --gid 1001 --system nodejs
RUN adduser --system --uid 1001 nextjs

# Change ownership
RUN chown -R nextjs:nodejs /app
USER nextjs

# Expose port
EXPOSE 3000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD curl -f http://localhost:3000/health || exit 1

# Start the application
CMD ["bun", "run", "dist/server.js"]`;

    return {
      path: 'Dockerfile',
      content,
      type: 'config'
    };
  }

  private generateDockerCompose(): GeneratedFile {
    const content = `version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: specflow_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis (optional, for caching/sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/specflow_api
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-this
      CORS_ORIGIN: http://localhost:3000,http://localhost:5173
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database migrations (run once)
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/specflow_api
    command: bun run db:migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./drizzle:/app/drizzle:ro
    restart: "no"

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: specflow_network`;

    return {
      path: 'docker-compose.yml',
      content,
      type: 'config'
    };
  }

  private generateDockerIgnore(): GeneratedFile {
    const content = `node_modules
npm-debug.log
.git
.gitignore
README.md
.env
.env.*
.nyc_output
coverage
.DS_Store
*.log
dist
.cache
.next
out
build
.vercel
.netlify`;

    return {
      path: '.dockerignore',
      content,
      type: 'config'
    };
  }

  private generateGitIgnore(): GeneratedFile {
    const content = `# Dependencies
node_modules/
bun.lockb

# Production build
dist/
build/

# Environment variables
.env
.env.local
.env.production

# Database
drizzle/

# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Coverage directory used by tools like istanbul
coverage/
*.lcov

# Compiled binary addons
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# ESLint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# Editor directories and files
.vscode/
.idea/
*.swp
*.swo
*~

# OS generated files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# Temporary files
tmp/
temp/`;

    return {
      path: '.gitignore',
      content,
      type: 'config'
    };
  }

  private generateReadme(config: SpecFlowConfig): GeneratedFile {
    const content = `# ${config.project.name} API

${config.project.description || 'API generated by SpecFlow'}

## Getting Started

### Prerequisites

- [Bun](https://bun.sh) (latest version)
- [PostgreSQL](https://postgresql.org) (v12 or higher)
- [Docker](https://docker.com) (optional, for containerized setup)

### Installation

1. **Clone the repository:**
   \`\`\`bash
   git clone <your-repo-url>
   cd ${config.project.name}
   \`\`\`

2. **Install dependencies:**
   \`\`\`bash
   bun install
   \`\`\`

3. **Set up environment variables:**
   \`\`\`bash
   cp .env.example .env
   # Edit .env with your configuration
   \`\`\`

4. **Set up the database:**
   \`\`\`bash
   # Create database (if not using Docker)
   createdb specflow_api
   
   # Run migrations
   bun run db:migrate
   \`\`\`

5. **Start the development server:**
   \`\`\`bash
   bun run dev
   \`\`\`

The API will be available at \`http://localhost:3000\`.

## Development

### Available Scripts

- \`bun run dev\` - Start development server with hot reload
- \`bun run start\` - Start production server
- \`bun run build\` - Build for production
- \`bun run test\` - Run tests
- \`bun run test:watch\` - Run tests in watch mode
- \`bun run db:generate\` - Generate database migrations
- \`bun run db:migrate\` - Run database migrations
- \`bun run db:studio\` - Open Drizzle Studio (database GUI)
- \`bun run typecheck\` - Type check TypeScript files
- \`bun run lint\` - Run ESLint
- \`bun run format\` - Format code with Prettier

### Project Structure

\`\`\`
src/
├── db/
│   ├── client.ts          # Database connection
│   ├── schema.ts          # Drizzle table definitions
│   └── migrate.ts         # Migration runner
├── lib/
│   ├── auth.ts            # Authentication utilities
│   ├── errors.ts          # Error handling
│   └── password.ts        # Password utilities
├── middleware/
│   ├── auth.ts            # Authentication middleware
│   ├── cors.ts            # CORS configuration
│   └── rate-limit.ts      # Rate limiting
├── routes/
│   └── ...                # API route handlers
├── schemas/
│   └── ...                # Zod validation schemas
└── server.ts              # Main application entry point
\`\`\`

## Docker Setup

### Development with Docker Compose

\`\`\`bash
# Start all services (API, PostgreSQL, Redis)
docker-compose up

# Start in background
docker-compose up -d

# View logs
docker-compose logs -f api

# Stop all services
docker-compose down
\`\`\`

### Production Deployment

\`\`\`bash
# Build production image
docker build -t ${config.project.name}-api .

# Run production container
docker run -p 3000:3000 \\
  -e DATABASE_URL=your-postgres-url \\
  -e JWT_SECRET=your-secret \\
  ${config.project.name}-api
\`\`\`

## API Documentation

### Health Check
- **GET** \`/health\` - API health status

### Authentication
${config.project.description?.includes('auth') ? '- **POST** `/auth/register` - User registration\n- **POST** `/auth/login` - User login' : ''}

For complete API documentation, see the generated OpenAPI specification or use the interactive docs.

## Environment Variables

| Variable | Description | Default |
|----------|-------------|---------|
| \`PORT\` | Server port | \`3000\` |
| \`NODE_ENV\` | Environment | \`development\` |
| \`DATABASE_URL\` | PostgreSQL connection string | - |
| \`JWT_SECRET\` | JWT signing secret | - |
| \`CORS_ORIGIN\` | Allowed CORS origins | \`http://localhost:3000\` |

See \`.env.example\` for a complete list.

## Database

This project uses [Drizzle ORM](https://orm.drizzle.team) with PostgreSQL.

### Migrations

\`\`\`bash
# Generate migration after schema changes
bun run db:generate

# Apply migrations
bun run db:migrate

# Reset database (development only)
bun run db:reset
\`\`\`

### Database Studio

\`\`\`bash
# Open Drizzle Studio for visual database management
bun run db:studio
\`\`\`

## Testing

\`\`\`bash
# Run all tests
bun run test

# Run tests in watch mode
bun run test:watch

# Run tests with coverage
bun run test:coverage
\`\`\`

## Production Deployment

### Environment Setup

1. Set production environment variables
2. Run database migrations
3. Build the application
4. Start the production server

### Recommended Deployment Options

- **Docker**: Use the provided Dockerfile and docker-compose.yml
- **Cloud Platforms**: Deploy to platforms like Railway, Render, or Fly.io
- **VPS**: Use PM2 or systemd for process management

## Contributing

1. Fork the repository
2. Create a feature branch
3. Make your changes
4. Add tests if applicable
5. Run the test suite
6. Submit a pull request

## License

This project is licensed under the MIT License - see the LICENSE file for details.

---

Generated by [SpecFlow](https://github.com/specflow/llm-backend-framework) 🚀`;

    return {
      path: 'README.md',
      content,
      type: 'config'
    };
  }
}